from pathlib import Path


path = Path(r"d:\Poetry\Poetry-AI\frontend\src\pages\MyLearning.tsx")
lines = path.read_text(encoding="utf-8").splitlines()

updates = {
    1364: '      description: "建议回到学情总览收拢本周练测、错题与记忆状态，再根据薄弱点安排下一轮巩固。"',
    1368: '        { label: "看复习计划", to: "/my-learning?tab=plan&from=create" },',
    1369: '        { label: "去图谱延展", to: "/graph?from=my_learning" },',
    1377: '      title: "图谱发现已形成，下一步把薄弱点转成行动",',
    1378: '      description: "建议选择一个薄弱节点，进入对应题组练测；若错因已明确，可回错题本或计划面板收束。"',
    1381: '        { label: "去练测", to: "/practice?entry=practice&auto=1&source=graph", variant: "primary" as const },',
    1383: '        { label: "看复习计划", to: "/my-learning?tab=plan&from=graph" },',
    1391: '    description: "先在总览里确认本周薄弱点，再进入错题本或计划面板安排下一步。"',
    1405: '\t label: "掌握率趋势",',
    1409: '\t ? `当前强项是 ${diagnosisStrongestDimension.label}，薄弱点集中在 ${diagnosisWeakestDimension.label}。`',
    1410: '\t : "近 30 天整体掌握率正在形成稳定基线。",',
    1413: '\t label: "知识点覆盖",',
    1414: '\t value: "4 类",',
    1415: '\t detail: "按题型、朝代、题材和记忆巩固四个维度整理当前覆盖面。",',
    1420: '\t detail: `待复习 ${overviewWrongPending} 题，计划待完成 ${planTaskStats.pending} 项。`,',
    1429: '\t value: learningSummaryLoading ? "同步中" : `${learningSummary?.overview?.accuracy30d ?? diagnosisAverageRate}%`,',
    1430: '\t detail: "来自 /api/user/learning-summary。班级聚合接口接入前，不展示伪造班级均值。",',
    1433: '\t label: "待处理错题",',
    1435: '\t detail: "来自真实错题本统计，可作为后续班级共性错因聚合的基线。",',
    1438: '\t label: "计划待完成",',
    1440: '\t detail: "来自当前复习计划执行状态，暂不冒充班级作业完成率。",',
    1443: '\t label: "当前薄弱点",',
    1446: '\t ? `个人维度正确率 ${diagnosisWeakestDimension.rate}%，后续可映射到班级错题分布。`',
    1447: '\t : "等待更多练测数据后生成真实薄弱维度。",',
    1460: '\t description: "依据题型表现估算当前整体稳定度。",',
    1465: '\t description: "结合朝代维度表现判断理解基础。",',
    1470: '\t description: "关注送别、思乡、山水等主题的迁移情况。",',
    1475: '\t description: "依据待处理任务粗估当前复习压力。",',
    1485: '\t { label: "第1周", value: Math.max(35, diagnosisAverageRate - 9) },',
    1486: '\t { label: "第2周", value: Math.max(40, diagnosisAverageRate - 5) },',
    1487: '\t { label: "第3周", value: Math.max(45, diagnosisAverageRate - 2) },',
    1488: '\t { label: "第4周", value: diagnosisAverageRate },',
    1512: '\t const weakest = diagnosisWeakestDimension ? `${diagnosisWeakestDimension.label}${diagnosisWeakestDimension.rate}%` : "暂无明显薄弱点";',
    1514: '\t return `当前整体掌握率约 ${diagnosisAverageRate}%，强项为 ${strongest}，当前最需要补齐的是 ${weakest}。`;',
    1525: '\t "正在根据近期练测、错题与复习数据生成学情解读。",',
    1532: '\t "建议先围绕当前薄弱点安排一轮专项练测，再回到错题与记忆训练做收束。",',
    1536: '\t const reportTitle = "诗境通阶段学情报告";',
    1543: '\t .map((item) => `- **${escapeMarkdown(item.label)} ${item.mastery}%**：${escapeMarkdown(item.description)}`)',
    1546: '\t .map((item) => `- **${escapeMarkdown(item.title)}**：${escapeMarkdown(item.detail)}`)',
    1552: '\t `- 生成时间：${generatedAt}`,',
    1553: '\t `- 学情摘要：${overviewNarrative}`,',
    1561: '\t "## 近 30 天趋势",',
    1565: '\t "## 知识点覆盖",',
    1569: '\t "## AI 学情解读与教学建议",',
    1580: '\t `<li><strong>${escapeHtml(item.label)}：</strong>${escapeHtml(String(item.mastery))}% / ${escapeHtml(item.description)}</li>`,',
    1588: '\t <h1 class="report-title">诗境通阶段学情报告</h1>',
    1589: '\t <p class="report-subtitle">生成时间：${escapeHtml(generatedAt)}<br />${escapeHtml(overviewNarrative)}</p>',
    1622: '\t setStudyReportMessage(opened ? "已打开学情报告打印页，可在浏览器中另存为 PDF。" : "浏览器拦截了报告窗口，请允许弹窗后重试。");',
    1628: '\t const downloaded = downloadTextFile(`诗境通学情报告_${timestamp}.md`, markdown);',
    1629: '\t setStudyReportMessage(downloaded ? "已导出 Markdown 学情报告。" : "当前环境不支持下载 Markdown 学情报告。");',
    1646: '\t setPlanReminderMessage("当前浏览器不支持通知提醒。");',
    1658: '\t setPlanReminderMessage("未获得通知权限，请在浏览器中允许通知。");',
    1663: '\t setPlanReminderMessage("复习提醒已开启。");',
    1669: '\t setPlanReminderMessage("复习提醒已关闭。");',
    1674: '\t setPlanReminderMessage("当前浏览器不支持通知提醒。");',
    1679: '\t setPlanReminderMessage("通知权限未开启，无法发送测试提醒。");',
    1682: '\t new Notification("诗境通复习提醒", {',
    1683: '\t body: "这是一条测试提醒：你可以按计划完成今天的复习任务。",',
    1686: '\t setPlanReminderMessage("测试提醒已发送。");',
    1703: '\t const title = "诗境通复习提醒";',
    1704: '\t const body = `当前还有 ${planTaskStats.pending} 项任务未完成，建议优先处理高优先级任务。`;',
    1919: 'wrongbook: "我的错题本",',
    1925: 'overview: "汇总当前掌握率、趋势变化与下一步学习建议。",',
    1926: 'wrongbook: "处理待复习错题，并在列表、统计、趋势之间切换。",',
    1927: 'favorites: "管理收藏诗词，沉淀重点作品与笔记。",',
    1928: 'diagnosis: "查看最弱维度、考试诊断与专项回补入口。",',
    1929: 'plan: "安排今日复习任务，推进执行并管理提醒。",',
    1933: '{ id: "workspace" as const, label: "错题处理区" },',
    2376: '<Suspense fallback={<MyLearningLazyFallback label="错题工作区概览" />}>',
}

for line_no, content in updates.items():
    lines[line_no - 1] = content

path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"updated {len(updates)} lines")
